### ISSUE TITLE
Is it possible to add a label/name to the card?

### ISSUE THREAD

**Issue by jgeorge1983** [Sese-Schneider/ha-energy-overview-card#10]
If I wanted to add multiple power meter smart plugs using this card it would be handy to have a lable option per one so we can differentiate.

I did try adding lable/name in case it was already there

**Comment by Sese-Schneider** [comment]
@jgeorge1983 you could use `label_leading` or `label_trailing`, refer to the README for details.
Or do you want to add a "heading" for each entity?

**Comment by jgeorge1983** [comment]
Yeh i was more of a heading i was after, maybe on the same line as the v/a/w??

also it may just be me not being very intelligent, but what is power_factor?

**Comment by Sese-Schneider** [comment]
Same line might be a bit much information. I think design wise putting it above might be better. I will see what I can do. @jgeorge1983 

Power factor is a measurement of efficency, ratio of working power, measured in kilowatts (kW), to apparent power, measured in kilovolt amperes (kVA). Efficiency losses come from converting three phase power to one phase to use in homes.
But I'm no expert here, YouTube has good resources explaining it.

**Comment by jgeorge1983** [comment]
awesome, thanks for he quick response.

**Comment by Sese-Schneider** [comment]
Hi @jgeorge1983,
Your requested feature is now available in the latest release!
Thank you for your patience.

**Comment by jgeorge1983** [comment]
Great update, thank you very much!!
