### ISSUE TITLE
Add parameter current frequency

### ISSUE THREAD

**Issue by oleggogol** [Sese-Schneider/ha-energy-overview-card#11]
Could you add one more parameter to the line - current frequency.

**Comment by Sese-Schneider** [comment]
@oleggogol can you please provide me with an example screenshot of the entity containing this value?
Where exactly in the parameter line would you locate the frequency?

**Comment by oleggogol** [comment]
if I understood you correctly,
I am sending a screenshot:
![freq](https://user-images.githubusercontent.com/65493035/221615037-e4b05758-d005-4adf-a0e4-30a7b7751c16.jpg)

**Comment by Sese-Schneider** [comment]
@oleggogol the requested change is now available in the the prerelease `2.2.0-dev.1`.
I will keep this issue open until it is officially released in the stable channel.

**Comment by oleggogol** [comment]
Thanks for the quick update.
