### ISSUE TITLE
Power value in kW

### ISSUE THREAD

**Issue by andysaab** [Sese-Schneider/ha-energy-overview-card#12]
Hello!
Thanks for a good job, very useful card.
Could you add the possibility to use power in kW due most meter provide it in kW, not in W only. 
Otherwise card not animated.
Thanks in advance!

**Comment by WHagenauw** [comment]
I have the same issue

**Comment by Sese-Schneider** [comment]
I will add an option 👍🏼

**Comment by marcelvandorp** [comment]
Hi,

I have the same issue. My sensor does provide the attribute 'unit_of_measurement', which is correctly set to 'kW' 

Is that useful?

**Comment by Sese-Schneider** [comment]
@marcelvandorp yes, thank you for that detail

**Comment by Sese-Schneider** [comment]
@andysaab the requested change is now available in the the prerelease `2.2.0-dev.2`.
I will keep this issue open until it is officially released in the stable channel.

/cc: @WHagenauw @marcelvandorp

**Comment by andysaab** [comment]
Hi, Sese! 
On latest release it's working fine! 
Tnx a lot!
