### ISSUE TITLE
Voltage and Current are too close to each other

### ISSUE THREAD

**Issue by WHagenauw** [Sese-Schneider/ha-energy-overview-card#13]
very nice overview. I like it. The voltage and Current are close to each other. Maybe center all 3 over the entire length but also when e.g. power factor is not used.

**Comment by Sese-Schneider** [comment]
@WHagenauw can you send me a screenshot? what is the width of your card?

**Comment by WHagenauw** [comment]
The width doesn't really matter in what I mean. As you can see in the screenshot the Voltage and Current are close to each other and the Watt is almost at the right.
![Screenshot_20230301_191541_Home Assistant](https://user-images.githubusercontent.com/80526682/222227236-781cae34-87ee-4e06-8952-1821cb34cd14.jpg)

**Comment by Sese-Schneider** [comment]
@WHagenauw got it! This is a design choice I made because those two values are related, and essentially combine to form the power. (P = U * I)
Should I add a flag to evenly space all the parameters?

**Comment by WHagenauw** [comment]
Ofcourse they are al related to each other but space them looks nicer in my opinion. That way you can read them better. But can be a personal choice at least give them a little more space between them 🙂

**Comment by Sese-Schneider** [comment]
@WHagenauw is [Card Mod](https://github.com/thomasloven/lovelace-card-mod) an option for you?
All properties have CSS classes which could be modified by you individually.
