### ISSUE TITLE
Support power factor of max 1

### ISSUE THREAD

**Issue by andriej** [Sese-Schneider/ha-energy-overview-card#14]
Really nice card - used it straight away.

Although please make an option (true/false?) for power factor being either 0-100% or 0-1, as i.e. my electricity meter calculates it with total of 1 max (which seems ok verifying that with Wiki too: https://en.wikipedia.org/wiki/Power_factor )

**Comment by Sese-Schneider** [comment]
@andriej what's the unit type of the entity providing the value? I think I could try to detect the unit and adjust the UI accordingly

**Comment by andriej** [comment]
It's `cosϕ` although I've set it accordingly to reports from meter via modbus.

**Comment by Sese-Schneider** [comment]
@andriej the requested change is now available in the the prerelease `2.2.0-dev.2`.
I will keep this issue open until it is officially released in the stable channel.
