### ISSUE TITLE
Invert sensor for Goodwe inverter?

### ISSUE THREAD

**Issue by TommySharpNZ** [Sese-Schneider/ha-energy-overview-card#16]
When I'm using 100 watts from the grid my Goodwe sensor output -100w so the flow on this card is the wrong way round. Could you add an option to invert the sensor?

**Comment by Sese-Schneider** [comment]
I'll add an option to invert the animation 👍🏼

**Comment by ChristophCaina** [comment]
thanks :)
That's also valid for SolarEdge Inverters - and probably for many others as well 👍

**Comment by Sese-Schneider** [comment]
Hi @TommySharpNZ @ChristophCaina,
Your requested feature is now available in the latest release!
Thank you for your patience.

**Comment by ChristophCaina** [comment]
i've added the inverted: true option - but the animation does not change... ?

**Comment by Sese-Schneider** [comment]
@ChristophCaina care to share your config with me please?
Please also make sure to do a fresh reload of HA, the caching is very aggressive. (you can see the installed version in the JS console)

**Comment by ChristophCaina** [comment]
ok, seems to be a caching issue ... tried with Edge (even after restart and ctrl+f5) which did not help... while on Edge it seems to be working as expected.
