### ISSUE TITLE
Feature Request: Different view for long names

### ISSUE THREAD

**Issue by JurajNyiri** [Sese-Schneider/ha-energy-overview-card#19]
Hello,

Great card!

I would like to have an option to change the view of the card so that the label is on top of the line, so that it looks more consistent if you use different length of label_leading or label_trailing (see screenshot)

![image](https://user-images.githubusercontent.com/5785999/222936459-3ab62804-7fb6-490d-bf71-7e38fab00072.png)

**Comment by Sese-Schneider** [comment]
Hi, thank you for your request.
I've already been working on a title field, as of this feature request: https://github.com/Sese-Schneider/ha-energy-overview-card/issues/10
I will close this issue as duplicate, but I will add the field hopefully this week!

**Comment by Sese-Schneider** [comment]
Hi @JurajNyiri,
Your requested feature is now available in the latest release!
Thank you for your patience.
