### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by GeraldPape** [Sese-Schneider/ha-energy-overview-card#29]
I have set sorting to `order_by:current` but this takes no effect:
![grafik](https://github.com/Sese-Schneider/ha-energy-overview-card/assets/72608781/6f6ecf76-f43a-49e4-85c0-e33053d38eaa)

**Comment by Sese-Schneider** [comment]
@GeraldPape that's weird! I assume this is because of the different orders of magnitude in the units 🤔 
I will have a look.
Would you be able to share your full config with me?

**Comment by mx-vatte** [comment]
I can confirm that the ordering/sorting is also not working for me.

<img width="371" alt="image" src="https://github.com/Sese-Schneider/ha-energy-overview-card/assets/123895372/517a1869-ed63-4bc6-94e1-6c6dec8bbf26">

`type: custom:energy-overview-card
entities:
  - power: sensor.ug_backofen_power
    voltage: sensor.ug_backofen_voltage
    current: sensor.ug_backofen_current
    name: UG Backofen
  - power: sensor.ug_backofen_2_power
    voltage: sensor.ug_backofen_2_voltage
    current: sensor.ug_backofen_2_current
    name: UG Backofen 2
  - power: sensor.ug_wz_tv_power
    voltage: sensor.ug_wz_tv_voltage
    current: sensor.ug_wz_tv_current
    name: UG WZ TV
  - power: sensor.schreibtisch_patrick_power
    voltage: sensor.schreibtisch_patrick_voltage
    current: sensor.schreibtisch_patrick_current
    name: Schreibtisch Patrick
  - power: sensor.ug_waschmaschine_power
    voltage: sensor.ug_waschmaschine_voltage
    current: sensor.ug_waschmaschine_current
    name: UG Waschmaschine
  - power: sensor.ug_trockner_power
    voltage: sensor.ug_trockner_voltage
    current: sensor.ug_trockner_current
    name: UG Trockner
  - power: sensor.schreibtisch_sandra_power
    voltage: sensor.schreibtisch_sandra_voltage
    current: sensor.schreibtisch_sandra_current
    name: Schreibtisch Sandra
  - power: sensor.ug_bad_lampe_power
    voltage: sensor.ug_bad_lampe_voltage
    current: sensor.ug_bad_lampe_current
    name: UG Bad Lampe
  - power: sensor.treppe_power
    voltage: sensor.treppe_voltage
    current: sensor.treppe_current
    name: Treppe
  - power: sensor.ug_kuehlschrank_power
    voltage: sensor.ug_kuehlschrank_voltage
    current: sensor.ug_kuehlschrank_current
    name: UG Kuehlschrank
  - power: sensor.ug_kuehlschrank_2_power
    voltage: sensor.ug_kuehlschrank_2_voltage
    current: sensor.ug_kuehlschrank_2_current
    name: UG Kuehlschrank 2
  - power: sensor.ug_kammer_kuehlschrank_power
    voltage: sensor.ug_kammer_kuehlschrank_voltage
    current: sensor.ug_kammer_kuehlschrank_current
    name: UG Kammer Kuehlschrank
  - power: sensor.ug_geschirrspuler_power
    voltage: sensor.ug_geschirrspuler_voltage
    current: sensor.ug_geschirrspuler_current
    name: UG Geschirrspueler
  - power: sensor.ug_geschirrspuehler_2_power
    voltage: sensor.ug_geschirrspuehler_2_voltage
    current: sensor.ug_geschirrspuehler_2_current
    name: UG Geschirrspueler 2
  - power: sensor.ug_gefrierschrank_gross_power
    voltage: sensor.ug_gefrierschrank_gross_voltage
    current: sensor.ug_gefrierschrank_gross_current
    name: UG Gefrierschrank gross
  - power: sensor.ug_gefrierschrank_klein_power
    voltage: sensor.ug_gefrierschrank_klein_voltage
    current: sensor.ug_gefrierschrank_klein_current
    name: UG Gefrierschrank klein
  - power: sensor.og_az_drucker_ir_heizung_power
    voltage: sensor.og_az_drucker_ir_heizung_voltage
    current: sensor.og_az_drucker_ir_heizung_current
    name: OG AZ Drucker+IR+Heizung
order_by: power
animation:
  inverted: false
`

**Comment by borodaaaaa** [comment]
+ 1 Soring does not work 

![image](https://github.com/Sese-Schneider/ha-energy-overview-card/assets/110703905/db581be4-1170-4796-90db-4f8753b11d22)

**Comment by mx-vatte** [comment]
Thank you very much! The sorting now works in general. But there is the a problem with sorting over units e.g. W and kW.

![Screenshot_20231229-132148_Home_Assistant](https://github.com/Sese-Schneider/ha-energy-overview-card/assets/123895372/f51a7fb5-cb08-4ebc-adaf-884294d418c3)

**Comment by Sese-Schneider** [comment]
@mx-vatte this is a known limitation right now unfortunately ...
I have to trade of being able to sort different types (power, voltage, etc) and converting numbers to compare.

Feel free to open a new issue for this please or try to implement a fix.
You can set the unit of measurement in your HA entity to have it uniform across the card, and have the sorting working for you.
