### ISSUE TITLE
Is there a title field available?

### ISSUE THREAD

**Issue by PulsarFX** [Sese-Schneider/ha-energy-overview-card#31]
In most HA cards it is possible to add an optional title to the card, like shown here for entities:
![grafik](https://github.com/Sese-Schneider/ha-energy-overview-card/assets/4960210/df703a25-4fc9-42b3-a96e-1d11bb08c6cc)

It would be nice to have this field in energy overview card, too. Currently, the layout looks somewhat misaligned without a title ;)

![grafik](https://github.com/Sese-Schneider/ha-energy-overview-card/assets/4960210/a32b671e-a31d-47f8-b96d-af45d172e27f)

**Comment by Sese-Schneider** [comment]
There is currently no title field available.

Adding it might not be a big effort, I try to do it but can't promise a timeline.
PRs are welcome!

**Comment by PulsarFX** [comment]
Works great! Thanks!
