### ISSUE TITLE
Allow for animation overwrites per entity & add css classes everywhere for custom styling options

### ISSUE THREAD

**Issue by IntExCZ** [Sese-Schneider/ha-energy-overview-card#7]
Very nice card! :-)

Please add individual animation settings to every entity instead of global setting.
That would be good if used entities does not have same power maximum.

Please add to all HTML elements an unique CSS class for customizing (via card_mod).

Please wrap entity value and entity unit into idividual CSS classed <span> for customizing (indentation, color, etc.)

Thank you! :-)

**Comment by Sese-Schneider** [comment]
@IntExCZ thank you for your suggestions.
I will get to this hopefully soon and can integrate your requirements.

- I aim to do individual animation settings as an overwrite to the globals, keeping them if users like to change globally
  - power maximum is purely for animation, so this will be in the same change
- unique css classes for everything are a great idea, I will make sure to add this

**Comment by Sese-Schneider** [comment]
@IntExCZ your feature requests are now available in `v2.1.0`.
Please let me know if you have any issues.
Thank you for your suggestions!
