### ISSUE TITLE
Support rounding of measurement values

### ISSUE THREAD

**Issue by jacobstim** [Sese-Schneider/ha-energy-overview-card#9]
When utilizing sensor entities that provide a lot of numbers in their floating point data, the data starts overlapping and is no longer visible:

![image](https://user-images.githubusercontent.com/15199644/221419642-ddba017a-2375-48d5-b3f2-ef20b7990a96.png)

A workaround is to generate a template sensor that provides the rounding, but given that most power entity viewers already provide a way of rounding data, it's probably more convenient to users to support this out of the box, e.g. to round to 1 or 2 digits (or make it configurable per measurement).

**Comment by Sese-Schneider** [comment]
I will have a look at this and try to improve that, maybe add a configuration option.
Thank you @jacobstim

**Comment by Sese-Schneider** [comment]
@jacobstim what an coincidence; Home Assistant just released the option to set sensor display precision!
Have a look here: https://www.home-assistant.io/blog/2023/03/01/release-20233/#sensor-display-precision

Does this work for you?

**Comment by jacobstim** [comment]
Hi Sebastian @Sese-Schneider, that's indeed a good way of dealing with it! What a coincidence and indeed a good way to solve the problem :).
